#--------------------------------------#
#    GiveExp Configuration!      #
#--------------------------------------#
#-------------------------------------------------#
# Delays can be set up when giving exp #
#------------------------------------------------#

options:
  delay: 0
